name: self-hosted runner
on: push
#1 2
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
         
         while IFS= read -r line; do
              echo "Text read from file: $line"
              echo ::set-env name=$line
         done < use.env
      - name: Dump Env context
        if: env.SOMEVAR == '55'
        env: 
          ENV_CONTEXT: ${{ toJson(env) }}
        run: |
          echo "$ENV_CONTEXT"
          echo $SOMEVAR
      
