name: test my FirstJSAction
on:   push

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: zhuorg/FirstJSAction@master
      with:
        who-to-greet: 80345688
  
